"""Add phone_number and address to OrdersHistory

Revision ID: dfbf962b3939
Revises: 
Create Date: 2025-09-21 17:18:02.306563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbf962b3939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_history', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
